### ISSUE TITLE
Unsend DMs does not unsend

### ISSUE THREAD

**Issue by wefalltomorrow** [thoughtsunificator/instagram-dm-unsender#18]
I click Unsend All, it scrolls a bit and then a pop-up states "IDMU: Finished" without actually unsending/deleting anything.

Based in Australia, not sure if Instagram has updated the site for this location.

**Comment by thoughtsunificator** [comment]
What version are you using, what browser (and its version) ? Also, if you could send me the console logs after running it that'd be great.

**Comment by wefalltomorrow** [comment]
Tried both latest and stable, on both Firefox (v117.0.1) with Tampermonkey and on Vivaldi (v6.2.3105.48) with Violentmonkey. Also attempted with VPN connected to USA and clearing cookies/cache but same results unfortunately.

![image](https://github.com/thoughtsunificator/instagram-dm-unsender/assets/45746576/da95ee55-120e-44ba-b872-3ba4db75c800)

[www.instagram.com-1695194187782.log](https://github.com/thoughtsunificator/instagram-dm-unsender/files/12669869/www.instagram.com-1695194187782.log)

**Comment by thoughtsunificator** [comment]
I just released [v0.5.13](https://github.com/thoughtsunificator/instagram-dm-unsender/releases/tag/v0.5.13). It seems to work on my end. 

I'll be closing this issue for now.

**Comment by wefalltomorrow** [comment]
> I just released [v0.5.13](https://github.com/thoughtsunificator/instagram-dm-unsender/releases/tag/v0.5.13). It seems to work on my end.
> 
> I'll be closing this issue for now.

Unfortunately the same issue occurs for me even with this new update :(

**Comment by wefalltomorrow** [comment]
Haven't tested yet, but might be a good idea to wait for user input before closing issues 😅

**Comment by Ash1R** [comment]
@thoughtsunificator similar issue for me with it scrolling to IDMU: Finished but no unsending. 
console only gave "undefined" at ui.js:93
I am on 0.5.14

**Comment by thoughtsunificator** [comment]
@Ash1R Can you send me your console logs ?
