### ISSUE TITLE
Similar to prev. issue, doesn't seem to be working

### ISSUE THREAD

**Issue by Ash1R** [thoughtsunificator/instagram-dm-unsender#20]
Upon clicking Unsend all DMs, it scrolls to the top but does not delete anything. Once it reaches the beginning of the DM, it just stops while still showing the "Stop Processing" button with the rest of the screen darkened. 

The console is showing nothing other than
<img width="407" alt="Screen Shot 2023-09-20 at 10 45 26 PM" src="https://github.com/thoughtsunificator/instagram-dm-unsender/assets/69091220/cb1f607c-3654-4869-8795-1b6d7c3b4520">

I am in the U.S, if that helps. 

<img width="423" alt="Screen Shot 2023-09-20 at 11 04 04 PM" src="https://github.com/thoughtsunificator/instagram-dm-unsender/assets/69091220/fc07c09f-4231-4af8-a5f3-cc89b643633e">
<img width="515" alt="Screen Shot 2023-09-20 at 11 04 41 PM" src="https://github.com/thoughtsunificator/instagram-dm-unsender/assets/69091220/532b578f-5b73-4808-b92e-867fd7334b3c">

Here is how an example unsend process looks like ^

**Comment by thoughtsunificator** [comment]
I fixed an issue where the loading would never stop. It's out in [v0.5.14](https://github.com/thoughtsunificator/instagram-dm-unsender/releases/tag/v0.5.14).
