### ISSUE TITLE
seems to just say "Stop processing" forever and not actually delete anything

### ISSUE THREAD

**Issue by ThighNir** [thoughtsunificator/instagram-dm-unsender#23]
Whenever i click "Unsend all dms" It just starts processing forever with seemingly no end. I even tried loading every single message first and nothing happened at all. I've been letting it process for about 30 minutes now

**Comment by thoughtsunificator** [comment]
Could you give us me some technical details : 

- What browser (and its version)
- What version of IDMU you are using
- Your console logs
