### ISSUE TITLE
India User , Scrpit not working for me 

### ISSUE THREAD

**Issue by PlasticIngot** [thoughtsunificator/instagram-dm-unsender#29]
I am noob to all of this ,

Here is my problem: I am from India, and the messages I send on Instagram appear on the right side. However, I think the script is trying to unsend messages from the left side. It works great for reels, though. Also, I think the script is trying to find three dots near messages (more options), but in my case, that option appears on both sides (the messages I sent and the messages I received). Not with the reels, though. I think that's the reason reels work great for this script. So, are there any settings I can use to fix it? I am a noob, as I said earlier, so tell me in detail what to do.

![Screenshot (130)](https://github.com/thoughtsunificator/instagram-dm-unsender/assets/152162809/280ef885-736c-4c02-b1f7-4fa405b84cc3)

**Comment by thoughtsunificator** [comment]
The dots are supposed to be on both side, so don't worry about that.

Could you tell me then where it fails to work by performing the steps to reproduce the issue and then includes your full console logs here ?

Finally, if you could include a screenshot of the messages it fails to unsend if there's any?

**Comment by thoughtsunificator** [comment]
A new version (v0.5.19) has been released.

Please open a new issue following the provided template if your problem persists.
