### ISSUE TITLE
Grammatical errors in the README.md file.

### ISSUE THREAD

**Issue by SyntheticAdil** [thoughtsunificator/instagram-dm-unsender#32]
Hello there Developer!

I recently used your project to delete some threads of mine off of Instagram DMs & I loved it.
But I couldn't help but notice a few mistakes on the README file while I was going through it. For example, "the userscript allow a user to batch unsend DM in a thread on the web version of [instagram.com](https://www.instagram.com/)" has an error at _'allow'_ . (It should be 'allows') and a few additional ones which I noticed. Additionally. I'd like to make some changes to the sentence structuring to make it sound more professional, if needed be. 
Once again, loved your project & I'd love to contribute to it to make it better.
Hoping that my pull request gets accepted haha.

**Comment by thoughtsunificator** [comment]
Merged, thanks for the feedback.
