### ISSUE TITLE
How can I change the script to click the More button on the right side of the chat?

### ISSUE THREAD

**Issue by gitgud5** [thoughtsunificator/instagram-dm-unsender#34]
First of all, great script, really good work, thank you so much. I just want to know one thing here.
I think Instagram UI hasn't updated for me so it is selecting the More button of chats on the left side where there is no unsend option. Can you help me understand how can I change it so it will select the More button of the messages on the right?
As for screenshot idk how to include that because it happens really quickly and it can be understood what's happening by looking at it. I did notice aria button should be on both sides and the function is my message was made to check for that. But I don't see the modal popping up on the right side for me sadly.

**Comment by gitgud5** [comment]
Made a screenshot
![image](https://github.com/thoughtsunificator/instagram-dm-unsender/assets/49618496/67fbdb2c-25f2-4b17-b0c9-ab129ef5e746)

**Comment by thoughtsunificator** [comment]
It should click all more buttons to check for the presence of a "Unsend" menu item, it does not matter if the message is located on the right or on the left. 

Could you tell me what is working and what is not and also include your browser console logs, the version of the script you are using, your browser and its version. 
I made [a wiki](https://github.com/thoughtsunificator/instagram-dm-unsender/wiki/How-to-export-the-console-logs-of-my-browser) on how to do export browser logs.

**Comment by gitgud5** [comment]
Alright so, basically it is not deleting the messages. Sorry for the late reply.
[console-export-2024-2-28_12-14-34.txt](https://github.com/thoughtsunificator/instagram-dm-unsender/files/14430114/console-export-2024-2-28_12-14-34.txt)
I have attached the logs file too. IT is not opening and deleting the messages and as said before only the more button of the left side messages if pressed for some reason. and it doesn't delete messages first time. Also I think another thing that happens is that once I stop and then start running the script without refreshing, it basically just deletes some messages but that is really slow so I am not sure what is going on there.

**Comment by bitraver** [comment]
I am facing the same issue with @gitgud5

**Comment by DetFrog** [comment]
Me too @gitgud5

**Comment by thoughtsunificator** [comment]
A new version (v0.5.19) has been released.
