### ISSUE TITLE
Queue size

### ISSUE THREAD

**Issue by PerrellLaquariusBrown** [thoughtsunificator/instagram-dm-unsender#37]
Hi

I have a question regarding the queue size. After some time the queue stopped and when I ran the program again, it went through the messages it went with the first queue and did this time nothing. Is there a way to increase the lifespan of a queue by editing the code? I don't have any experience with programming, so I'm quite behind when it comes to code reading.

Thank you for your time.

**Comment by zlairon** [comment]
> Hi
> 
> I have a question regarding the queue size. After some time the queue stopped and when I ran the program again, it went through the messages it went with the first queue and did this time nothing. Is there a way to increase the lifespan of a queue by editing the code? I don't have any experience with programming, so I'm quite behind when it comes to code reading.
> 
> Thank you for your time.

Same question. It scans and deletes a certain number of texts, and then scans the first batch again and scrolls up slowly to delete the new ones.

**Comment by thoughtsunificator** [comment]
I am not sure what your problem is… You could maybe open another issue using the issued template :
![image](https://github.com/thoughtsunificator/instagram-dm-unsender/assets/85041649/3ab39c7a-89d6-478e-9e53-c12abcf6f2ec)
