### ISSUE TITLE
Only one option showing to Unsend

### ISSUE THREAD

**Issue by rakitanc** [thoughtsunificator/instagram-dm-unsender#40]
Please resolve this as the script is working fine otherwise 

![Screenshot from 2024-05-29 00-30-43](https://github.com/thoughtsunificator/instagram-dm-unsender/assets/64612555/60bef293-e80c-4594-8cd1-cdf10505901e)

 - OS: Pop os 22.04
 - Browser - Chrome
 - Version Version 124.0.6367.207 (Official Build) (64-bit)
 - Language

**Comment by ssobnomnom** [comment]
Same issue.

**Comment by thoughtsunificator** [comment]
Are we talking about the unsent count here?
