### ISSUE TITLE
"Unsend all DMs" option only; Unsent stopped.

### ISSUE THREAD

**Issue by ssobnomnom** [thoughtsunificator/instagram-dm-unsender#42]
The three (3) buttons mentioned are lacking two (2). Only the 'Unsend all DMs' are present. The script works as it will unsend messages but after a minute or two, it will stop unsending messages. It will keep on running but isn't unsending anything anymore at this point. Reloading doesn't work.

[www.instagram.com-1719418186153.log](https://github.com/user-attachments/files/15992305/www.instagram.com-1719418186153.log)

 - OS: Windows 11 Home; Version 23H2; OS build 22631.3737
 - Browser: Chrome
 - Version: 126.0.6478.126 (Official Build) (64-bit)
 - Language: English (US)

**Comment by ssobnomnom** [comment]
<img width="278" alt="image" src="https://github.com/thoughtsunificator/instagram-dm-unsender/assets/173936510/874dd90e-d2d6-4314-85e1-01f18bb5fe03">

**Comment by thoughtsunificator** [comment]
>but after a minute or two, it will stop unsending messages
How many messages are we talking about here?

**Comment by ssobnomnom** [comment]
All the way to the beginning.

**Comment by thoughtsunificator** [comment]
> It was unsending for a few minutes

My question was how many messages (approximately) get unsent and how many do not get unsent?

**Comment by DevilofParadis** [comment]
Bro can anyone tell which script i have to put in developer console and how to put that please can anyone tell?

**Comment by thoughtsunificator** [comment]
> > The three (3) buttons mentioned are lacking two (2). Only the 'Unsend all DMs' are present. The script works as it will unsend messages but after a minute or two, it will stop unsending messages. It will keep on running but isn't unsending anything anymore at this point. Reloading doesn't work.
> 
> Same problem, is there a way to put a loop so even if the unsending stops, it starts again by itself ?

I recommend you open a new issue with the provided template, and I will do my best to fix the issue ASAP.
