### ISSUE TITLE
Any help on getting this to work in the UK?

### ISSUE THREAD

**Issue by butimaymeanno** [thoughtsunificator/instagram-dm-unsender#48]
**How impactful is the issue**

 Critical

**Describe the bug**

My dms aren't being unsent; code isn't working for me

**How to reproduce the bug**

Using the code as intended

**Logs**

(Paste the file here.)

Unable to.

**Screenshots**

![image](https://github.com/user-attachments/assets/be425ba5-7dfc-4346-b0de-e6e79ee957cd)

**Desktop (please complete the following information):**

Windows, Chrome, Latest stable release, UK/EU version

**Additional context**

(Write your answer here.)

**Comment by butimaymeanno** [comment]
Apologies for not being able to get the logs file, I am not too proficient in technology

**Comment by thoughtsunificator** [comment]
Hello,

I'll need the exact steps you took that resulted in the bug, as well as a description less vague than "it's not working".

For the logs file, when you open an issue there is a step-by-step guide that explains how you can retrieve those, if you can point to me what it is that you don't understand maybe I can guide you in getting the logs.
